#!/usr/bin/env python

# ADC Pins

ADC_MUX_SIGNAL_PIN = 0
ADC_FRONT_RANGE_PIN = 1
ADC_BACK_RANGE_PIN = 2
ADC_LEFT_RANGE_PIN = 3
ADC_RIGHT_RANGE_PIN = 4
ADC_BATTERY_LEVEL_PIN = 5
ADC_BATTERY_STATUS_PIN_1 = 6
ADC_BATTERY_STATUS_PIN_2 = 7


#MUX Pins
MUX_WATER_LEVEL2_PIN = 0
MUX_WATER_LEVEL1_PIN = 1
MUX_WATER_LEVEL0_PIN = 2
MUX_NUTRIENT_LEVEL2_PIN = 3
MUX_NUTRIENT_LEVEL1_PIN = 4
MUX_NUTRIENT_LEVEL0_PIN = 5
MUX_FORCE_SENSOR_PIN = 6


# GPIO Pins
GPIO_MUX_S2_PIN = 8
GPIO_MUX_S1_PIN = 9
GPIO_MUX_S0_PIN = 10
GPIO_MUX_ENABLE_PIN = 11
GPIO_WATER_PUMP_PIN = 12
GPIO_NUTRIENT_PUMP_PIN = 13

