#!/usr/bin/env python

# ADC Pins
ADC_WATER_LEVEL2_PIN = 0
ADC_WATER_LEVEL1_PIN = 1
ADC_WATER_LEVEL0_PIN = 2
ADC_NUTRIENT_LEVEL2_PIN = 3
ADC_NUTRIENT_LEVEL1_PIN = 4
ADC_NUTRIENT_LEVEL0_PIN = 5
ADC_FORCE_SENSOR_PIN = 6
ADC_BATTERY_STATUS_PIN_1 = 7
ADC_BATTERY_STATUS_PIN_2 = 8
ADC_BATTERY_STATUS_PIN_3 = 9
ADC_RANGE_RIGHT_PIN
ADC_RANGE_LEFT_PIN
ADC_RANGE_RIGHT_PIN
ADC_RANGE_LEFT_PIN

# GPIO Pins
GPIO_WATER_PUMP_PIN = 2
GPIO_NUTRIENT_PUMP_PIN = 3
